### ISSUE TITLE
A question about coverage2cytosine

### ISSUE THREAD

**Issue by jmsong2** [steichten/brachy_reference_methylomes#1]
Dear steichten,

I found a command in the 1_Bd21_analysis.sh :

coverage2cytosine --genome_folder ../rawdata/genomes/Bd21/ -CX ../0_initial_mapping_output/Bd21_wgbspipeline_2016-09-20-14-09-31/5_output_files/Bd21_CpG.bed.bismark.cov -o allcytosines.txt

why could the CpG.bed.bismark.cov create allcytosines.txt? how about the other bismark.cov files like CHH.bed.bismark.cov or CHG.bed.bismark.cov generated by the Bismark methylation extractor?

Look forward to your kind adive.

Regard,
JiaMing

**Comment by steichten** [comment]
The -CX flag in v0.13.0 was required for the non CG contexts. Without it, it would only report in the CG context. 

This line was done to get all cytosines in the genome across all contexts. It just used the CpG.bed.bismark.cov file as a placeholder. The resulting file is not specifically for the CG context, just to have a record of every genomic C for comparison to the results.

Hope that helps.

-steve

**Comment by jmsong2** [comment]
Thanks for your timely reply.  It's very helpful!
